import { MCPTool, ToolOutput, ArtilleryResult } from '../types.js';
import { ArtilleryWrapper } from '../lib/artillery.js';
import { ProjectConfig } from '../lib/config-loader.js';
import path from 'path';

/**
 * Project launcher — opinionated wrapper around `artillery run` that reads
 * flow→path mapping, environment list, default tags, and output-dir from a
 * project config file (`.artillery-mcp.config.json`).
 *
 * Registered only when the loaded config has a non-empty `flows` map.
 * Without a config, this tool is not exposed at all.
 */
export class RunProjectLtTool implements MCPTool {
  readonly name = 'run_project_lt';
  readonly description =
    'Run a pre-configured project LT scenario with opinionated defaults. Reads flows, environments, default tags, and output dir from .artillery-mcp.config.json. Use this when you have multiple named flows and want one-liner invocations.';

  readonly inputSchema: Record<string, unknown>;

  constructor(
    private artillery: ArtilleryWrapper,
    private projectConfig: ProjectConfig,
    private projectRoot: string
  ) {
    const flowNames = Object.keys(projectConfig.flows ?? {});
    const envNames = projectConfig.environments ?? [];
    this.inputSchema = {
      type: 'object',
      properties: {
        flow: flowNames.length ? { type: 'string', enum: flowNames, description: 'Named flow from config.flows' } : { type: 'string' },
        environment: envNames.length ? { type: 'string', enum: envNames, description: 'Environment from config.environments (passed to artillery as -e)' } : { type: 'string' },
        record: { type: 'boolean', default: true, description: 'Record to Artillery Cloud (requires ARTILLERY_CLOUD_API_KEY in env)' },
        name: { type: 'string', description: 'Run name (default: autogenerated from flow+env+timestamp)' },
        note: { type: 'string', description: '--note annotation' },
        extraTags: { type: 'string', description: 'Comma-separated key:value tags appended to defaults' },
        templateVars: { type: 'object', additionalProperties: { type: 'string' }, description: 'Values substituted into config.tagTemplates (e.g. {"round": "21"})' },
        outputJson: { type: 'string', description: 'Override output JSON path (default: <outputDir>/<flow>-<env>-<ts>.json)' },
        reportHtml: { type: 'string' },
        variables: { description: 'Extra -v JSON passed to artillery' },
        overrides: { description: 'Extra --overrides JSON' },
        validateOnly: { type: 'boolean' },
        extraArgs: { type: 'array', items: { type: 'string' } }
      },
      required: ['flow', 'environment']
    };
  }

  async call(
    request: any
  ): Promise<ToolOutput<ArtilleryResult & { command: string; tags: string; configPath: string }>> {
    try {
      const args = request.params?.arguments || request.params || {};
      const flow: string = args.flow;
      const envName: string = args.environment;
      const flows = this.projectConfig.flows ?? {};
      const envs = this.projectConfig.environments ?? [];

      if (!flows[flow]) {
        throw new Error(
          `Unknown flow "${flow}". Configured flows: ${Object.keys(flows).join(', ') || '(none)'}. Edit .artillery-mcp.config.json → flows.`
        );
      }
      if (envs.length > 0 && !envs.includes(envName)) {
        throw new Error(
          `Unknown environment "${envName}". Configured: ${envs.join(', ')}. Edit .artillery-mcp.config.json → environments.`
        );
      }

      const configPath = path.isAbsolute(flows[flow])
        ? flows[flow]
        : path.join(this.projectRoot, flows[flow]);
      const record = args.record !== false;

      const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
      const runName = args.name || `${flow}-${envName}-${timestamp}`;

      // Build tags: defaultTags + tagTemplates + extraTags
      const tagParts: string[] = [];
      const defaultTags = this.projectConfig.defaultTags ?? {};
      for (const [k, v] of Object.entries(defaultTags)) tagParts.push(`${k}:${v}`);

      const templateVars: Record<string, string> = {
        flow,
        env: envName,
        ...(args.templateVars ?? {})
      };
      for (const template of this.projectConfig.tagTemplates ?? []) {
        const rendered = template.replace(/\{(\w+)\}/g, (_, key) => templateVars[key] ?? '');
        if (rendered && !rendered.includes('{') && rendered.split(':').every(Boolean)) {
          tagParts.push(rendered);
        }
      }
      if (args.extraTags) tagParts.push(args.extraTags);
      const tags = tagParts.join(',');

      const outputDir = this.projectConfig.outputDir
        ? path.isAbsolute(this.projectConfig.outputDir)
          ? this.projectConfig.outputDir
          : path.join(this.projectRoot, this.projectConfig.outputDir)
        : this.projectRoot;
      const outputJson = args.outputJson || path.join(outputDir, `${flow}-${envName}-${timestamp}.json`);

      const runOptions = {
        outputJson,
        reportHtml: args.reportHtml,
        cwd: this.projectRoot,
        record,
        name: runName,
        note: args.note,
        tags: tags || undefined,
        environment: envName,
        variables: args.variables,
        overrides: args.overrides,
        validateOnly: args.validateOnly,
        extraArgs: args.extraArgs
      };

      const result = await this.artillery.runTestFromFile(configPath, runOptions);

      const commandParts = ['artillery run'];
      if (record) commandParts.push('--record');
      commandParts.push(`--name "${runName}"`);
      if (tags) commandParts.push(`--tags "${tags}"`);
      commandParts.push(`-e ${envName}`);
      if (args.note) commandParts.push(`--note "${args.note}"`);
      commandParts.push(`-o "${outputJson}"`);
      commandParts.push(configPath);

      return {
        status: 'ok',
        tool: this.name,
        data: { ...result, command: commandParts.join(' '), tags, configPath }
      };
    } catch (error) {
      return {
        status: 'error',
        tool: this.name,
        error: {
          code: 'EXECUTION_ERROR',
          message: error instanceof Error ? error.message : 'Unknown error occurred',
          details: {
            tool: this.name,
            arguments: request.params?.arguments || request.params
          }
        }
      };
    }
  }
}
